language: node_js
node_js:
- '8.11'
install:
- npm install
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: gxRmRTpcUigpBFqH9b31j768VkuEiu0tgK0cILdCegdjaRIuEIMapfYlgi0MIafo5erhrasUVU8v0ciBFY4mnpYyRXre9l+ag+hPj28lCgQiJEcxc0ldzC0u65A5m8JM/CsL/O+nYNIiOuoebE/0DQ1GO7e46Ux5+olswm3XEHeK3/9uD3eORf8YVOBp2ZkoSnF3d5n/XHhgTR8ErM8TmsVVmygcbWe6eVMzvOa3zs5DHZ/IRLLJ9kYWPEQZbC3HT0wDgot6iXZAOXN/bfNRB1sz1BM8ewq6zv2X6xHoLqbQnX6vmFk2c45WuTPCiq5OVR8MZai2SD8HCzldZDgr8zH3ZzPmJriOUKqRxTeHhNjJ1B5kqOghC+gbNPIk2NvBN40PQf5tUgMdTN623R5cvsvZ9BTt6A4ix721LfP89Itdsj8lDjv9H7XV3RJ27UNkPReD8PWly6mNcSNC16WnMR7MBHhtjC3rmFEdpncwq2G3sW3pkArmLHoG9GGUibGMIZl5ZruiQ7ozrPPLBy7riKXHMvgu/Kk56tzcMZCW+lArZXu8n+i+jWZ6U0zxBDqL2t94/TUUB4mjgvJ8rHN0M63SG5K6TcvyTp85BAbr4FMa/+TzSngUEhP4jQP4yVggwXqN5PDPPnIqMTyTCXgPlQYaV1V4L4dMGbJHqg82Vfo=
  app: br-com-lazarodm-blog
