language: generic
branches:
  only:
  - master
  - hugo
services:
- docker
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_0.55.5_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.55.5_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
script:
- hugo
after_success:
- docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
- docker build -t registry.heroku.com/br-com-lazarodm-blog/web .
- docker push registry.heroku.com/br-com-lazarodm-blog/web
env:
  global:
  - secure: R0Qi1Flu5lW4WpmV8bHCtBCzwFerBxHAtiD6zQLoLmn3NbcGfKjomimMN4jaRuGS5UNfj4/5eNY9XeBzEq+3swKP4tEVjGA6EiK3anM9/1kMIbCcDZbX0WbQLzMWUe3dGaULFBszy4v4IlNB9zb2OsXqIemQajxUE7OpPjP43qUpz44YWKIpoIe0BqkzUZRkxyFWEPIJP+QYBACEG8NpA1pi1R1m3D6a3QOjimM1+u9YhKpvpP6fU1m+3fbN4A3he6zldJzqm3F0OLrbPe98Z0oWy3bxaW9pFNL5s5nZWgGRYHOMzQxjLevjS3YyD4LV9WtWuWmyGL7/dvVs+hpucaPEdXztAgwquax/V8su7UAz9QZWOttNAEt9Q0c3FX8SlXdmdEjywZSa/xJqjBCLgTFFoXG7sSdHOKS/Ygyg9L1OWipET/Ixs5mcy/tRP92MhGgzD4X0HpQTwt39YIrCuqJ+V4zK/gziRWXnHh/doy4rorW2w9u+KoeiMKiCzcgY0dU6dy2ywss6tDVEIknB0A4YAXNamHafv/bkp2p3p9jH6mZF1Oa+1Xl+lYicqDL4P+Nk6O1J1dWoQ5HRAb8rAjpb7sUoH3tiRy+XS3CxD+bC0P3bxRiDnlqfyOZk000TNvfygNObY9GxsgD2Ijy0Zw2y+tjXUZly8XgoE08Pwjg=
