title = "Lazaro's Blog"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/lazarodanillomenezes"
  youtube = ""
  github = "https://www.github.com/lazaromenezes"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lazarodm"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hero/IMG_8875.jpg"
  recent_posts_number = 5
