baseURL: http://www.lazarodm.com.br/
theme: ananke
MetaDataFormat: yaml
SectionPagesMenu: main
Paginate: 10
googleAnalytics: UA-163694959-1
enableRobotsTXT: true
disqusShortName: lazarodm

markup:
  goldmark:
    renderer:
      unsafe: true

# Language
defaultContentLanguage: pt 
languages:
  pt:
    title: Blog do Lalão
    weight: 0
    contentDir: content/pt-br

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: ''
  description: ''
  instagram: 'https://www.instagram.com/lazarodanillomenezes'
  github: 'https://www.github.com/lazaromenezes'
  linkedin: 'https://www.linkedin.com/in/lazarodm'
  background_color_class: bg-black
  featured_image: /images/hero/IMG_8875.jpg
  recent_posts_number: 5
  post_content_classes: sans-serif
  show_reading_time: true
  commentoEnabled: true
  custom_css: 
  - "css/theme-adjustments.css"
