name: Blog CD

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and Push image 
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: br-com-lazarodm-blog
          heroku_email: lazarodm@gmail.com
          usedocker: true
