name: Blog CD

on:
  push:
    branches:
      - main 

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Deploy to Digital Ocean
        uses: digitalocean/app_action/deploy@v2
        env:
          HUGO_EXTENDED: 1
        with:
           token: ${{ secrets.DO_ACCESS_TOKEN }}
           project_id: ${{ secrets.DO_PROJECT_ID }}
           print_build_logs: true
           print_deploy_logs: true

  post-deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Dispatch repository upload
        run: |
          curl -u lazaromenezes:${{secrets.GH_ACCESS_TOKEN}} -X POST -d '{"event_type":"blog_deployed"}' https://api.github.com/repos/lazaromenezes/lazaromenezes/dispatches
