name: Blog CD

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/blog:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Login to Azure'
        uses: 'azure/login@v1'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: blog 
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/blog:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_UASERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: blog.lazarodm.com.br
          location: 'brazil south'
    
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Dispatch repository upload
        run: |
          curl -u lazaromenezes:${{secrets.ACCESS_TOKEN}} -X POST -d '{"event_type":"blog_deployed"}' https://api.github.com/repos/lazaromenezes/lazaromenezes/dispatches
